source 'https://rubygems.org'

gem 'bundle'
gem 'rake'
gem 'ashikawa-core'
gem 'yell'
gem 'redis'
gem 'nokogiri'
gem 'elasticsearch'
gem 'rb-readline'
gem 'oauth'
gem 'koala'
gem 'fb_graph'
gem 'i18n', '~> 0.7.0'